### ISSUE TITLE
Providing -s argument for simulation causes error, error simulating with k and alpha

### ISSUE THREAD

**Issue by xylebori** [hahnlab/CAFExp#11]
cafexp -s1000 -p10  -l 0.0025 -f mammals_root_dist.txt -o 1rate_L0025_P10_SIM -t Mammals_test.tre
Option -s cannot be provided an argument if -f is specified.

I was able to get this to run a simulation if I used this but it simulated 10k families

cafexp -s -p10  -l 0.0025 -f mammals_root_dist.txt -o 1rate_L0025_P10_SIM -t Mammals_test.tre

**Comment by benfulton** [comment]
This is as designed. The number of simulations is equal to the sum total of families in the rootdist. (The second column). Is this something worth changing? Maybe draw randomly from the rootdist until the number of simulations is reached?
