### ISSUE TITLE
Not finishing run

### ISSUE THREAD

**Issue by xylebori** [hahnlab/CAFExp#13]
First I simulate data with a Lambda of 0.0025 and 1 rate category

cafexp -s -p10  -l0.0025 -f mammals_root_dist.txt -o 1rate_L0025_P10_SIM -t Mammals_test.tre

Now Run CAFE on the simulated data set.
cafexp  -p10  -i SIM_1rate_L0025_P10_LEAF.txt  -o 1rate_Est_on_1RATE_L0025 -t Mammals_test.tre

#######First: Lambda does not match simulated lambda of 0.0025 #######
Completed 25 iterations
Best match is: 0.0032891474445718,
#######

#######Second: Seems to be computing P-values forever#######
Starting inference processes for Base model

Inferring processes for Base model
Computing pvalues...

I waited for hours without this finishing.

**Comment by xylebori** [comment]
If I input lambda to match that which the data was simulated under:

cafexp  -p10  -l0.0025 -i SIM_1rate_L0025_P10_LEAF.txt  -o 1rate_FIXEDLAMDA_on_1RATE_L0025 -t Mammals_test.tre

Starting inference processes for Base model

Inferring processes for Base model
Computing pvalues...

******

While this does not seem to finish either (seems to be computing pvalues forever, however I did run this in screen so maybe if I check back tomorrow it will have finished)  the likelihood is calculated and I can see it in the 'results' file. 

Model Base Result: 179015
Lambda:          0.0025

Here, the lambda matches the simulated value as enforced above, however the likelihood is much worse than the under the lambda value above.

**Comment by benfulton** [comment]
Put some effort into parallelizing the pvalue calculations
