### ISSUE TITLE
Estimate p-values relative to the families in the highest rate class.

### ISSUE THREAD

**Issue by xylebori** [hahnlab/CAFExp#19]
This is just regarding our discussion of estimating p-values based on the families that fall into the fastest category

**Comment by benfulton** [comment]
For each family we write out the pvalue and the calculated probabilities for for each category. Does this mean we want to only write out families for which the probability of the fastest category is the greatest?

**Comment by benfulton** [comment]
Added code in the gamma model to only include families for which the largest lambda multiplier probability was the highest. Then calculated pvalues using that largest lambda multiplier.
