### ISSUE TITLE
Estimate genome assembly error

### ISSUE THREAD

**Issue by SRodenburg** [hahnlab/CAFExp#25]
Hi,

First of all I am happy to see CAFE got way more efficient and user-friendly.
I have a question regarding the estimation of errormodels. In previous releases I've used (CAFE 4) I would use `caferror.py` to estimate the assembly error.
Is the assembly errormodel estimation step implemented in the general workflow of CAFE 5?

In `README.md` at [error model estimation](https://github.com/hahnlab/CAFExp#error-model-estimation) it seems an initial errormodel must be given using the `-e` flag. That got me confused.

Best regards,
Sander

**Comment by benfulton** [comment]
Right now, when the user specifies an error model, we use that model for reconstruction if the lambda is also given. If the lambda is being estimated and the user specifies an error model, an epsilon for the error model will be estimated instead.
