### ISSUE TITLE
summary of expanded, contacted and rapidly evolving genes in CAFE5

### ISSUE THREAD

**Issue by bioteksampath** [hahnlab/CAFExp#27]
Hi
Thanks for this tool, CAFE5 is much faster also has no hassle in preparing input files (filtration).

wondering, how to get the summary of expanded, contacted and rapidly evolving genes in CAFE5 (summary_run1_node.txt and summary_run1_pub.txt in Cafe4) output and corresponding Orthogroups (similar to CAFE4 - summary_run1_fams.txt). 

Not able to use cafe4 scripts as outputs are different in CAFE5, python_scripts/cafetutorial_report_analysis.py 
python_scripts/cafetutorial_draw_tree.py

And how to draw a tree using this output  python_scripts/cafetutorial_report_analysis.py 
Thanks
sam

**Comment by benfulton** [comment]
Hi Sam,

Thanks for trying out the application! The file in the output directory, "base_asr.tre" is in the NEXUS file format, so standard tree drawing programs such as Dendroscope can read them. The file "Base_change.tab" has the positive and negative changes for each family.

Let me know what other questions you have.

**Comment by xylebori** [comment]
Hi Sam,

Also, Base_family_results.txt  will give you the list of families that have a significant change in rate on at least one branch.  As Ben mentions, the base_change.tab file gives the change for each family at each node.  The Base_asr.tre file has the family counts reconstructed at each node and whether that count is significant will be marked with an asterisk.  As this is a beta release not all of the outputs have been updated for convenience but the information you seek can be easily viewed by parsing the _change.tab, _asr.tre, and _branch_probabilities.tab files.

**Comment by marcelauliano** [comment]
> Hi
> Thanks for this tool, CAFE5 is much faster also has no hassle in preparing input files (filtration).
> 
> wondering, how to get the summary of expanded, contacted and rapidly evolving genes in CAFE5 (summary_run1_node.txt and summary_run1_pub.txt in Cafe4) output and corresponding Orthogroups (similar to CAFE4 - summary_run1_fams.txt).
> 
> Not able to use cafe4 scripts as outputs are different in CAFE5, python_scripts/cafetutorial_report_analysis.py
> python_scripts/cafetutorial_draw_tree.py
> 
> And how to draw a tree using this output python_scripts/cafetutorial_report_analysis.py
> Thanks
> sam

Hey sam, have you produced parsers for those files to produce your tree? =) I can re-think this, but if you have script to to the parsing could you let me know? =) Thank you!

**Comment by xylebori** [comment]
Hello Marcella,

There are several ways of determining this.  All of the results are output in tab delimited format so typically it is just a matter of deciding what you want to look at.  I you go to the updated manual on GitHub located here<https://github.com/hahnlab/CAFE5> you will see I have included some simple parsing commands for the files that are already output.  We are working on doing some summary output files as part of the standard output as well that will write some of these numbers onto a tree, but this information is also already present in the “model”_clade_results.txt file. An example of the simple parsing you can do that I added to the manual are pictured below.

[cid:BE219D0F-BEC8-45A2-8214-4708C08677E7]


[cid:4E3E0BD7-B9D8-45FF-903C-A6370275C22F]


dv

On Mar 24, 2021, at 1:06 PM, Marcela Uliano-Silva ***@***.******@***.***>> wrote:

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.



Hi
Thanks for this tool, CAFE5 is much faster also has no hassle in preparing input files (filtration).

wondering, how to get the summary of expanded, contacted and rapidly evolving genes in CAFE5 (summary_run1_node.txt and summary_run1_pub.txt in Cafe4) output and corresponding Orthogroups (similar to CAFE4 - summary_run1_fams.txt).

Not able to use cafe4 scripts as outputs are different in CAFE5, python_scripts/cafetutorial_report_analysis.py
python_scripts/cafetutorial_draw_tree.py

And how to draw a tree using this output python_scripts/cafetutorial_report_analysis.py
Thanks
sam

Hey sam, have you produced parsers for those files to produce your tree? =) I can re-think this, but if you have script to to the parsing could you let me know? =) Thank you!

**Comment by marcelauliano** [comment]
Dear dv, 
Thanks a lot for adding some more explanation here and in the manual page. I think that with yours and benfulton's comments I'm getting there :)
Thank you!
