### ISSUE TITLE
Filtering the number of families

### ISSUE THREAD

**Issue by Edison2021** [hahnlab/CAFExp#28]
Hi Ben
At the very beginning of running, there is a message like " Filtering the number of families from: 23034 ==> 7183". What does that mean? Even if i use the script  clade_and_size_filter.py to filter my gene family, the cafe5 still gives me the filtering message.

2)Does cafe5 have option for λ≠μ.
3)Does Base_branch_probablilities.tab ONLY contain all significantly changing gene families at nodes or branches? 

Thanks
Edison

**Comment by benfulton** [comment]
Hi Edison,

The filter refers to the parsimony check that was implemented in earlier versions of CAFE:

 _The birth-death model of CAFE assumes at least one gene in the root of the species tree. This assumption may not be valid for families that were created after the most recent common ancestor of all species. The filter option ﬁlters out the families that are inferred (by parsimony) to have no genes in the root node of the species tree._

CAFE5 does not support separate birth/death rates at this time.
