### ISSUE TITLE
Errors when install CAFE5

### ISSUE THREAD

**Issue by wangzhennan14** [hahnlab/CAFExp#32]
Hi,
   When I install CAFE5, there was an errors as follow:
   g++ -std=c++11 -O3 -fopenmp -o bin/cafexp -I. obj/user_data.o obj/simulator.o obj/optimizer.o obj/cafexp.o obj/gene_family_reconstructor.o obj/gene_family.o obj/gamma.o obj/matrix_cache.o obj/gamma_core.o obj/base_model.o obj/error_model.o obj/io.o obj/core.o obj/lambda.o obj/root_equilibrium_distribution.o obj/clade.o obj/optimizer_scorer.o obj/poisson.o obj/root_distribution.o obj/execute.o obj/probability.o obj/main.o -lm
obj/clade.o：在函数‘parse_newick(std::string, bool)’中：
clade.cpp:(.text+0x451a)：对‘std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::bitset<11ul>)’未定义的引用
clade.cpp:(.text+0x4527)：对‘std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator()’未定义的引用
clade.cpp:(.text+0x4589)：对‘std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator!=(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)’未定义的引用
clade.cpp:(.text+0x459e)：对‘std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()’未定义的引用
clade.cpp:(.text+0x46f8)：对‘std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator++(int)’未定义的引用
clade.cpp:(.text+0x4741)：对‘std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()’未定义的引用
clade.cpp:(.text+0x48c9)：对‘std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()’未定义的引用
clade.cpp:(.text+0x4ab1)：对‘std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()’未定义的引用
clade.cpp:(.text+0x4b2a)：对‘std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()’未定义的引用
clade.cpp:(.text+0x4bb6)：对‘std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()’未定义的引用
obj/clade.o:clade.cpp:(.text+0x4d39): 跟着更多未定义的参考到 std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()
collect2: 错误：ld 返回 1
make: *** [bin/cafexp] 错误 1
     What is the matter? And how can I solve it? Thank you very much!
Best wish,
Wangzhennan

**Comment by benfulton** [comment]
This indicates that your compiler is missing some required C++ libraries. What compiler are you using, and what operating system?

**Comment by ChemaMD** [comment]
Hi, same problem here:

    [btx333@frontend11 CAFE]$ make
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/user_data.cpp -o obj/user_data.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/simulator.cpp -o obj/simulator.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/optimizer.cpp -o obj/optimizer.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/cafexp.cpp -o obj/cafexp.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/probability.cpp -o obj/probability.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/gene_family.cpp -o obj/gene_family.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/gamma.cpp -o obj/gamma.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/gamma_core.cpp -o obj/gamma_core.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/base_model.cpp -o obj/base_model.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/error_model.cpp -o obj/error_model.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/matrix_cache.cpp -o obj/matrix_cache.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/core.cpp -o obj/core.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/lambda.cpp -o obj/lambda.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/io.cpp -o obj/io.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/root_equilibrium_distribution.cpp -o obj/root_equilibrium_distribution.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/clade.cpp -o obj/clade.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/optimizer_scorer.cpp -o obj/optimizer_scorer.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/poisson.cpp -o obj/poisson.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/root_distribution.cpp -o obj/root_distribution.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/execute.cpp -o obj/execute.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/gene_family_reconstructor.cpp -o obj/gene_family_reconstructor.o
    g++ -std=c++11 -I. -O3 -include config.h -fopenmp -c main.cpp -o obj/main.o
    g++ -std=c++11 -O3 -fopenmp -o bin/cafexp -I. obj/user_data.o obj/simulator.o obj/optimizer.o     obj/cafexp.o obj/probability.o obj/gene_family.o obj/gamma.o obj/gamma_core.o obj/base_model.o obj/error_model.o obj/matrix_cache.o obj/core.o obj/lambda.o obj/io.o obj/root_equilibrium_distribution.o obj/clade.o obj/optimizer_scorer.o obj/poisson.o obj/root_distribution.o obj/execute.o obj/gene_family_reconstructor.o obj/main.o -lm
    obj/clade.o: In function `parse_newick(std::string, bool)':
    clade.cpp:(.text+0x451a): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::bitset<11ul>)'
    clade.cpp:(.text+0x4527): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator()'
    clade.cpp:(.text+0x4589): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator!=(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
    clade.cpp:(.text+0x459e): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
    clade.cpp:(.text+0x46f8): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator++(int)'
    clade.cpp:(.text+0x4741): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
    clade.cpp:(.text+0x48c9): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
    clade.cpp:(.text+0x4ab1): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
    clade.cpp:(.text+0x4b2a): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
    clade.cpp:(.text+0x4bb6): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
    obj/clade.o:clade.cpp:(.text+0x4d39): more undefined references to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()' follow
    collect2: error: ld returned 1 exit status
    make: *** [bin/cafexp] Error 1`

Which additional C++ library do we need to have to properly compile CAFE5.0.0 (beta2 release)? I'm using the following G++ compiler:

    [btx333@frontend11 ~]$ /usr/bin/g++ -v
    Using built-in specs.
    COLLECT_GCC=/usr/bin/g++
    COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
    Target: x86_64-redhat-linux
    Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
    Thread model: posix
    gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

Thank you very much for the help!

Chema

**Comment by benfulton** [comment]
GCC 4.8 is too old a compiler. You would need to upgrade to at least 4.9.
