### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by pnatsi** [hahnlab/CAFExp#35]
Hello.

During installation of CAFE5 I got the following errors:

g++ -std=c++11 -O3 -fopenmp -o bin/cafexp -I. obj/user_data.o obj/simulator.o obj/optimizer.o obj/likelihood_ratio.o obj/cafexp.o obj/gene_family.o obj/gamma.o obj/gene_family_reconstructor.o obj/matrix_cache.o obj/base_model.o obj/error_model.o obj/io.o obj/core.o obj/lambda.o obj/root_equilibrium_distribution.o obj/gamma_core.o obj/clade.o obj/optimizer_scorer.o obj/poisson.o obj/execute.o obj/probability.o obj/easylogging++.o obj/main.o -lm  
obj/clade.o: In function `parse_newick(std::string, bool)':
clade.cpp:(.text+0x3733): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::bitset<11ul>)'
clade.cpp:(.text+0x3740): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator()'
clade.cpp:(.text+0x37a1): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator!=(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
clade.cpp:(.text+0x37b6): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
clade.cpp:(.text+0x38eb): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator++(int)'
clade.cpp:(.text+0x3931): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
clade.cpp:(.text+0x39e9): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
clade.cpp:(.text+0x3ad9): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
clade.cpp:(.text+0x3b24): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
clade.cpp:(.text+0x3b81): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
obj/clade.o:clade.cpp:(.text+0x3cf9): more undefined references to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()' follow
collect2: error: ld returned 1 exit status
make: *** [bin/cafexp] Error 1

Any ideas what might be wrong?

Thank you

**Comment by benfulton** [comment]
You are probably using an older compiler. If you are using GCC, at least v4.9 is required.
