### ISSUE TITLE
What is the chi-square compare option and how to use it?

### ISSUE THREAD

**Issue by fohebert** [hahnlab/CAFExp#37]
Hi ! First off, thanks for putting together this nice program. Very useful and powerful program.

I'm still in the process of learning and understanding how to use it though, and I'm a bit confused by the documentation (e.g. the tutorial that comes with the latest distribution), which doesn't necessarily explain all the options/functionalities/possibilities of CAFExp (which would be version 5, right?). Totally understandable (requires a lot of time!).

One of the questions that I have (for now) is: what is the '-r' option and how to use it? In the help menu, it says ' --chisquare_compare, -r      Chi square compare'

What does it compare exactly and what is the argument that goes with the option? One or multiple files? Which one(s)?

Is this option designed to compare a simulated dataset vs. a "real" dataset?

Thanks for your time and your help.

**Comment by benfulton** [comment]
Hi,

Just for completion on this issue, the chi-squared option is being removed. Hopefully the latest version of the manuals explains the other options more completely :)
