### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by Callithrix-omics** [hahnlab/CAFExp#40]
Hello, 
I am trying to install CAFE5 Initial Release (beta 2) on Linux and got the following error upon make command: 

g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/base_model.cpp -o obj/base_model.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/cafexp.cpp -o obj/cafexp.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/clade.cpp -o obj/clade.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/core.cpp -o obj/core.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/error_model.cpp -o obj/error_model.o
src/error_model.cpp: In member function ‘void error_model::set_probabilities(size_t, std::vector<double>)’:
src/error_model.cpp:34:20: error: ‘runtime_error’ is not a member of ‘std’
   34 |         throw std::runtime_error("Cannot have a non-zero probability for family size 0 for negative deviation");
      |                    ^~~~~~~~~~~~~
src/error_model.cpp:39:20: error: ‘runtime_error’ is not a member of ‘std’
   39 |         throw std::runtime_error("Sum of probabilities must be equal to one");
      |                    ^~~~~~~~~~~~~
make: *** [Makefile:35: obj/error_model.o] Error 1

Any suggestions for how to fix error ? 

thank you.

**Comment by benfulton** [comment]
Please add

`#include <stdexcept>
`

Somewhere near the top of the file. I'm surprised this hasn't come up before. What operating system and compiler are you using?

**Comment by Callithrix-omics** [comment]
Thank you for the feedback. 

System info is 
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux

Compiler is 
gcc version 10.1.0 (GCC) 

Do you mean the Makefile? If so, the error is still there even after I put that in the file.

**Comment by benfulton** [comment]
No, sorry. The error is in the file src/error_model.cpp so it should go in there.

**Comment by Callithrix-omics** [comment]
now it gives error 
[CAFE]$ make
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/error_model.cpp -o obj/error_model.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/execute.cpp -o obj/execute.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/gamma_core.cpp -o obj/gamma_core.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/gamma.cpp -o obj/gamma.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/gene_family.cpp -o obj/gene_family.o
src/gene_family.cpp: In member function ‘int gene_family::get_species_size(std::string) const’:
src/gene_family.cpp:39:20: error: ‘runtime_error’ is not a member of ‘std’
   39 |         throw std::runtime_error(species + " was not found in gene family " + _id);
      |                    ^~~~~~~~~~~~~
make: *** [Makefile:37: obj/gene_family.o] Error 1

**Comment by benfulton** [comment]
Same solution. Now the error has moved to sec/gene_family.cpp though.

**Comment by Callithrix-omics** [comment]
thank you that seems to have solved the install. to just document the rest of the solution I got the following errors and repeated the solution for the files associated with the error. 

[CAFE]$ make 
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/gene_family.cpp -o obj/gene_family.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/gene_family_reconstructor.cpp -o obj/gene_family_reconstructor.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/io.cpp -o obj/io.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/lambda.cpp -o obj/lambda.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/matrix_cache.cpp -o obj/matrix_cache.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/optimizer.cpp -o obj/optimizer.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/optimizer_scorer.cpp -o obj/optimizer_scorer.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/poisson.cpp -o obj/poisson.o
In file included from src/poisson.cpp:7:
src/optimizer.h:157:66: error: expected class-name before ‘{’ token
  157 | class OptimizerInitializationFailure : public std::runtime_error {
      |                                                                  ^
src/optimizer.h: In constructor ‘OptimizerInitializationFailure::OptimizerInitializationFailure()’:
src/optimizer.h:159:58: error: expected class-name before ‘(’ token
  159 |     OptimizerInitializationFailure() : std::runtime_error("Failed to initialize any reasonable values")
      |                                                          ^
src/optimizer.h:159:58: error: expected ‘{’ before ‘(’ token
make: *** [Makefile:37: obj/poisson.o] Error 1
[CAFE]$ vim src/poisson.cpp
[CAFE]$ make 
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/poisson.cpp -o obj/poisson.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/probability.cpp -o obj/probability.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/root_distribution.cpp -o obj/root_distribution.o
src/root_distribution.cpp: In member function ‘int root_distribution::sum() const’:
src/root_distribution.cpp:54:20: error: ‘runtime_error’ is not a member of ‘std’
   54 |         throw std::runtime_error("Root distribution not created yet");
      |                    ^~~~~~~~~~~~~
src/root_distribution.cpp: In member function ‘int root_distribution::at(size_t) const’:
src/root_distribution.cpp:62:20: error: ‘out_of_range’ is not a member of ‘std’
   62 |         throw std::out_of_range("Root distribution value out of range");
      |                    ^~~~~~~~~~~~
make: *** [Makefile:37: obj/root_distribution.o] Error 1
[CAFE]$ vim src/root_distribution.cpp
[ CAFE]$ make
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/root_distribution.cpp -o obj/root_distribution.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/root_equilibrium_distribution.cpp -o obj/root_equilibrium_distribution.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/simulator.cpp -o obj/simulator.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/user_data.cpp -o obj/user_data.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp -c main.cpp -o obj/main.o
g++ -std=c++11 -O3 -fopenmp -o bin/cafexp -I. obj/base_model.o obj/cafexp.o obj/clade.o obj/core.o obj/error_model.o obj/execute.o obj/gamma_core.o obj/gamma.o obj/gene_family.o obj/gene_family_reconstructor.o obj/io.o obj/lambda.o obj/matrix_cache.o obj/optimizer.o obj/optimizer_scorer.o obj/poisson.o obj/probability.o obj/root_distribution.o obj/root_equilibrium_distribution.o obj/simulator.o obj/user_data.o obj/main.o -lm

**Comment by benfulton** [comment]
Fixed in https://github.com/hahnlab/CAFExp/commit/db461d0393fe39281ca6d659f02671fe4ba818b8
