### ISSUE TITLE
Simulating under -k categories outputs a nonsense file

### ISSUE THREAD

**Issue by xylebori** [hahnlab/CAFExp#6]
....
....
#marmoset
#mouserat
#rat
#mouse
617     617     617     617     617     1       617     617     617     617     617     617     617     617     617     617     617     617     617     617     617     617
617     617     617     617     617     1       617     617     617     617     617     617     617     617     617     617     617     617     617     617     617     617

**Comment by benfulton** [comment]
Result of one or more gamma categories being saturated on some branch lengths. Added some warnings and more obvious failed values for the file.
