### ISSUE TITLE
-s <num> flag in simulations produces 10k simulated families regardless of input

### ISSUE THREAD

**Issue by xylebori** [hahnlab/CAFExp#7]
cafexp -s 1000  -l 0.005 -p 10 -f mammals_root_dist.txt -o 1rate_L005_P10_SIM -t Mammals_test.tre

EVEN if I set this to 1000 it simulates 10k

Simulating 9989 families for model Base
Writing to simulation_1rate_L005_P10_SIM.txt

wc -l simulation_1rate_L005_P10_SIM.txt 
        10012 simulation_1rate_L005_P10_SIM.txt

**Comment by benfulton** [comment]
This needs to be done as -s1000 or --simulate=1000. As written the -s and -p parameters are default and there are unknown options "1000" and "10". Added code to print unknown options found and exit.
