### ISSUE TITLE
2nd to last column in simulated data sets is just 1 for every family

### ISSUE THREAD

**Issue by xylebori** [hahnlab/CAFExp#8]
cafexp -s 1000  -l 0.005 -p 10 -f mammals_root_dist.txt -o 1rate_L005_P10_SIM -t Mammals_test.tre

less simulation_1rate_L005_P10_SIM.txt  (numbering added by me)

1#mancat
2#cow
3#baboonchimpgibbonhumanmacaquemarmosetorang
4#baboonchimpgibbonhumanmacaqueorang
5#chimpgibbonhumanorang
6#babooncatchimpcowgibbonhorsehumanmacaquemarmosetmouseorangrat
7#chimphumanorang
8#chimphuman
9#chimp
10#human
11#catcowhorse
12#cathorse
13#cat
14#horse
15#orang
16#gibbon
17#baboonmacaque
18#macaque
19#baboon
20#marmoset
21#mouserat
22#rat
23#mouse
1       1       1       0       0       1       0       0       0       0       1       1       2       0       0       0       0       0       0       1       1       3       2       1       0
0       0       0       0       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       1       2       1       1       1
1       0       3       4       4       1       4       3       3       3       0       0       0       0       5       4       4       4       4       4       1       1       1       1       2
1       1       1       1       1       1       1       1       1       0       1       1       0       1       1       2       2       2       2       0       0       0       0       1       3
0       0       0       0       0       1       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       0       1       4

**Comment by benfulton** [comment]
We've been working in this area and can no longer reproduce this issue.
